### ISSUE TITLE
Short Code for notes/callouts?

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots.io#210]
Hi @GraysonNull @breezybaldwin I have a quick question -- in help.replicated.com we have a shortcode for notes/callouts, which supports both "info" and "warning" type notes:

<img width="744" alt="Screen Shot 2020-05-19 at 10 28 19 AM" src="https://user-images.githubusercontent.com/3730605/82345936-77703d80-99bb-11ea-980f-9504b5fd1cec.png">

<img width="694" alt="Screen Shot 2020-05-19 at 10 27 56 AM" src="https://user-images.githubusercontent.com/3730605/82345891-69bab800-99bb-11ea-824d-7606df55f4b4.png">

and can be invoked with something like:

```tpl
{{< note title="Initial Install Only" >}}
A file at `/etc/replicated.conf` will only be read on initial startup. It will never be written to, and once initial setup is complete and a license is installed, it will never be read again. (There are some exceptions to this rule, like changing the `DaemonAuthenticationPassword`, but in general it is not recommended to use `/etc/replicated.conf` after initial install).
{{< /note >}}
```

Would it be possible to design/provide something similar for kots.io ? (does this already exist and I don't know about it?

**Comment by GraysonNull** [comment]
@dexhorthy Nothing like this exists today in kots.io but it's certainly doable. @breezybaldwin if you've got a full plate i'm happy to take this, otherwise feel free to take a stab at it and ping me when you have a PR for review.

**Comment by breezybaldwin** [comment]
Oh yeah I can do this, easy peasy! :)

**Comment by dexhorthy** [comment]
@breezybaldwin I was trying to use some of these, but I'm missing an example of how to pull these in -- would you be able to provide an example of how to use?
