### ISSUE TITLE
KOTS Snapshots documentation suggests using opt-in for volume backups, which only works with Restic

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots.io#598]
Step 2 of https://kots.io/vendor/snapshots/configuring-backup/ discusses using the `backup.velero.io/backup-volumes` annotation to opt-in for specific volumes that should be backed up. This is documented under https://velero.io/docs/v1.7/restic/#using-opt-in-pod-volume-backup (which is Restic specific).

We're using GCP and the https://github.com/vmware-tanzu/velero-plugin-for-gcp plugin, and seeing all PVCs have volume snapshots created and restored despite only labeling a few specific volumes with the prior annotation. The behavior of plugins seems to be: if a PVC is included in the Velero backup, it will have a volume snapshot created for it that is later used during restores. This seems to interfere with our database backup/restore process, and has resulted in incomplete backups being restored.

My understanding of https://velero.io/docs/v1.7/resource-filtering/#veleroioexclude-from-backuptrue is that if we don't want to have volume snapshots created for a specific PVC, we need to explicitly include this label. That would be worth calling out as an explicit use-case in Step 3 of https://kots.io/vendor/snapshots/configuring-backup/, as it wasn't clear from those docs that plugins would create volume snapshots for all PVCs irrespective of Restic integration.

**Comment by AmberAlston** [comment]
Tracking in Replicated internal tracking in ticket 38953

**Comment by jonquil2002** [comment]
This issue is being tracked internally and will be addressed in the new docs repo: replicated-docs - instead of kots.io

As a result, I am closing this issue. Thanks for sharing this information, and we look forward to making this improvement in the docs now that we have launched our new docs website and repo.

**Comment by jonquil2002** [comment]
Per engineering, only restic is supported, not the Velero plugins. The docs were updated in this PR: https://github.com/replicatedhq/replicated-docs/pull/995
